TOPDIR := ../../..

include $(TOPDIR)/build/defines.mk

LIB := RtspClient

OBJS := RtspDak.o RtspDialogImpl.o RtspInterfaceImpl.o RtspMsgProcessor.o RtspUtils.o \
	RtspClient.o RtspClientFactory.o

INCDIR += .. ../../DataPostHouse
VPATH += ..

include $(TOPDIR)/build/common.mk



