TOPDIR := ../../..

include $(TOPDIR)/build/defines.mk

LIB := RtspServer

OBJS := RtspDak.o RtspDialogImpl.o RtspInterfaceImpl.o RtspMsgProcessor.o RtspUtils.o \
	RtspEngine.o

INCDIR += .. ../../DataPostHouse
VPATH += ..

include $(TOPDIR)/build/common.mk



