TOPDIR := ../..

include $(TOPDIR)/build/defines.mk

LIB := DataPostHouse
OBJS := DataDialogFactoryI.o DataPostHouseEnv.o DataPostHouseLinux.o DataCommunicator_linux.o DataCommunicatorSSL_linux.o   

include $(TOPDIR)/build/common.mk

